<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Project.charge.courses' => 'Corsi',
  'Project.charge.publicHoliday' => 'Festività',
  'Project.charge.sickLeave' => 'Malattia',
  'Project.charge.vacation' => 'Ferie',
  'Project.status.chargeItem' => 'Carico',
  'Project.status.closed' => 'Chiuso',
  'Project.status.deleted' => 'Cancellato',
  'Project.status.open' => 'Aperto',
  'Project.status.suspended' => 'Sospeso',
  'Task.priority.escalated' => 'Scalata',
  'Task.priority.high' => 'Alta',
  'Task.priority.low' => 'Bassa',
  'Task.priority.medium' => 'Media',
  'Task.type.bug' => 'Anomalia',
  'Task.type.enh' => 'Miglioria',
  'Task.type.task' => 'Generico',
  'TaskStatus.group.closed' => 'Chiuso',
  'TaskStatus.group.onHold' => 'In Attesa',
  'TaskStatus.group.open' => 'Aperto',
  'User.female' => 'Femmina',
  'User.male' => 'Maschio',
);
