<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Add Attachment' => 'Nuovo Allegato',
  'All Projects' => 'Tutti i Progetti',
  'All Tasks' => 'Tutte le Attività',
  'Application' => 'Applicazione',
  'Associate New User' => 'Associazione Nuovo Utente',
  'Attachments' => 'Allegati',
  'Backups' => 'Backup',
  'Charges' => 'Carichi',
  'Check for update' => 'Controlla aggiornamenti',
  'Config' => 'Configurazione',
  'Create' => 'Nuovo',
  'Create Charge' => 'Nuovo Carico',
  'Create Project' => 'Nuovo Progetto',
  'Create Role' => 'Nuovo Ruolo',
  'Create Task' => 'Nuova Attività',
  'Create Task Status' => 'Nuovo Stato',
  'Create Task Type' => 'Nuovo Tipo',
  'Create User' => 'Nuovo Utente',
  'Database Backups' => 'Backup del Database',
  'Delete Confirmation' => 'Conferma Eliminazione',
  'Edit Profile' => 'Modifica Profilo',
  'Edit Selected' => 'Modifica Selezionati',
  'Error' => 'Errore',
  'Export to' => 'Esporta in',
  'List' => 'Lista',
  'Login' => 'Login',
  'Logout' => 'Logout',
  'Manage' => 'Gestione',
  'Manage All' => 'Gestione Globale',
  'Manage All Charges' => 'Gestione Globale Carichi',
  'Manage Charges' => 'Gestione Carichi',
  'Manage Charges for <em>{name}</em>' => 'Gestione Carichi per <em>{name}</em>',
  'Manage Projects' => 'Gestione Progetti',
  'Manage Tasks' => 'Gestione Attività',
  'Manage Users' => 'Gestione Utenti',
  'My Charges' => 'I miei Carichi',
  'My Open Tasks' => 'Le mie Attività aperte',
  'My Projects' => 'I miei Progetti',
  'My Profile' => 'Profilo',
  'My Tasks' => 'Le mie Attività',
  'My Working On Tasks' => 'Le mie Attività in lavorazione',
  'Operations' => 'Operazioni',
  'Project.User.association.{project}' => 'Utenti associati a {project}',
  'Projects' => 'Progetti',
  'Roles' => 'Ruoli',
  'System' => 'Sistema',
  'Task Status' => 'Stati Attività',
  'Task Type' => 'Tipi Attività',
  'Tasks' => 'Attività',
  'Update' => 'Aggiorna',
  'Update Attachment' => 'Modifica Allegato',
  'Update Project' => 'Modifica Progetto',
  'Update Role' => 'Modifica Ruolo',
  'Update Task' => 'Modifica Attività',
  'Update Task Status "{name}"' => 'Modifica Stato Attività "{name}"',
  'Update Task Type "{name}"' => 'Modifica Tipo Attività "{name}"',
  'Update Tasks' => 'Modifica Attività',
  'Update User {name}' => 'Modifica Utente {name}',
  'Users' => 'Utenti',
  'Users Online' => 'Utenti Online',
  'View Attachment' => 'Vedi Allegato',
  //Comments
  'Comments' => 'Commenti',
  'Update Comment' => 'Modifica Commento'
);
