<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Project.charge.courses' => 'Cursos',
  'Project.charge.publicHoliday' => 'Asueto',
  'Project.charge.sickLeave' => 'Enfermadad',
  'Project.charge.vacation' => 'Vacaciones',
  'Project.status.chargeItem' => 'Cargar Item',
  'Project.status.closed' => 'Cerrado',
  'Project.status.deleted' => 'Eliminado',
  'Project.status.open' => 'Abierto',
  'Project.status.suspended' => 'Suspendido',
  'Task.priority.escalated' => 'Escalado',
  'Task.priority.high' => 'Alta',
  'Task.priority.low' => 'Baja',
  'Task.priority.medium' => 'Media',
  'Task.type.bug' => 'Bug',
  'Task.type.enh' => 'Mejora',
  'Task.type.task' => 'Tarea',
  'TaskStatus.group.closed' => 'Cerrada',
  'TaskStatus.group.onHold' => 'En Espera',
  'TaskStatus.group.open' => 'Abierta',
  'User.female' => 'Femenino',
  'User.male' => 'Masculino',
);
