<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Add Attachment' => 'Agregar Adjunto',
  'All Projects' => 'Todos los Proyectos',
  'All Tasks' => 'Todas las Tareas',
  'Application' => 'Aplicacion',
  'Associate New User' => 'Asociar Nuevo Usuario',
  'Attachments' => 'Adjuntos',
  'Backups' => 'Copias de Seguridad',
  'Charges' => 'Cargos',
  'Check for update' => 'Actualizacion',
  'Config' => 'Configurar',
  'Create' => 'Crear',
  'Create Charge' => 'Crear Cargo',
  'Create Project' => 'Crear Proyecto',
  'Create Role' => 'Crear Rol',
  'Create Task' => 'Crear Tarea',
  'Create Task Status' => 'Crear Estado de Tarea',
  'Create Task Type' => 'Crear Tipo de Tarea',
  'Create User' => 'Crear Usuario',
  'Database Backups' => 'Copia de Seguridad Base de Datos',
  'Delete Confirmation' => 'Confirmaci&oacute;n de Eliminaci&oacute;n',
  'Edit Profile' => 'Editar Perfil',
  'Edit Selected' => 'Editar Selecci&oacute;n',
  'Error' => 'Error',
  'Export to' => 'Exportar a',
  'List' => 'Lista',
  'Login' => 'Iniciar Sesion',
  'Logout' => 'Cerrar Sesion',
  'Manage' => 'Administrar',
  'Manage All' => 'Administrar Todo',
  'Manage All Charges' => 'Administrar Todos los Cargos',
  'Manage Charges' => 'Administrar Cargos',
  'Manage Charges for <em>{name}</em>' => 'Administrar Cargos para <em>{name}</em>',
  'Manage Projects' => 'Administrar Proyectos',
  'Manage Tasks' => 'Administrar Tareas',
  'Manage Users' => 'Administrar Usuarios',
  'My Charges' => 'Mis Cargos',
  'My Open Tasks' => 'Mis Tareas Abiertas',
  'My Profile' => 'Mi Perfil',
  'My Projects' => 'Mis Proyectos',
  'My Tasks' => 'Mis Tareas',
  'My Working On Tasks' => 'Tareas En Las Que Estoy Trabajando',
  'Operations' => 'Operaciones',
  'Project.User.association.{project}' => 'Usuarios asociados a {project}',
  'Projects' => 'Proyectos',
  'Roles' => 'Roles',
  'System' => 'Sistema',
  'Task Status' => 'Estado de Tarea',
  'Task Type' => 'Tipo de Tarea',
  'Tasks' => 'Tareas',
  'Update' => 'Actualizacion',
  'Update Attachment' => 'Actualizar Archivo Adjunto',
  'Update Project' => 'Actualizar Proyecto',
  'Update Role' => 'Actualizar Rol',
  'Update Task' => 'Actualizar Tarea',
  'Update Task Status "{name}"' => 'Actualizar estado de tarea "{name}"',
  'Update Task Type "{name}"' => 'Actualizar tipo de tarea "{name}"',
  'Update Tasks' => 'Actualizar Tareas',
  'Update User {name}' => 'Actualizar Usuario {name}',
  'Users' => 'Usuarios',
  'Users Online' => 'Usuarios en l&iacute;nea',
  'View Attachment' => 'Ver Archivos Adjuntos',
  //Comments
  'Comments' => 'Comments',
  'Update Comment' => 'Update Comment'
);
