<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Project.charge.courses' => 'Courses',
  'Project.charge.publicHoliday' => 'Public Holiday',
  'Project.charge.sickLeave' => 'Sick-leave',
  'Project.charge.vacation' => 'Vacation',
  'Project.status.chargeItem' => 'Charge Item',
  'Project.status.closed' => 'Closed',
  'Project.status.deleted' => 'Deleted',
  'Project.status.open' => 'Open',
  'Project.status.suspended' => 'Suspended',
  'Task.priority.escalated' => 'Escalated',
  'Task.priority.high' => 'High',
  'Task.priority.low' => 'Low',
  'Task.priority.medium' => 'Medium',
  'Task.type.bug' => 'Bug',
  'Task.type.enh' => 'Enhancement',
  'Task.type.task' => 'Task',
  'TaskStatus.group.closed' => 'Closed',
  'TaskStatus.group.onHold' => 'On Hold',
  'TaskStatus.group.open' => 'Open',
  'User.female' => 'Female',
  'User.male' => 'Male',
);
