<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Add Attachment' => 'Add Attachment',
  'All Projects' => 'All Projects',
  'All Tasks' => 'All Tasks',
  'Application' => 'Application',
  'Associate New User' => 'Associate New User',
  'Attachments' => 'Attachments',
  'Backups' => 'Backups',
  'Charges' => 'Charges',
  'Check for update' => 'Check for update',
  'Config' => 'Config',
  'Create' => 'Create',
  'Create Charge' => 'Create Charge',
  'Create Project' => 'Create Project',
  'Create Role' => 'Create Role',
  'Create Task' => 'Create Task',
  'Create Task Status' => 'Create Task Status',
  'Create Task Type' => 'Create Task Type',
  'Create User' => 'Create User',
  'Database Backups' => 'Database Backups',
  'Delete Confirmation' => 'Delete Confirmation',
  'Edit Profile' => 'Edit Profile',
  'Edit Selected' => 'Edit Selected',
  'Error' => 'Error',
  'Export to' => 'Export to',
  'List' => 'List',
  'Login' => 'Login',
  'Logout' => 'Logout',
  'Manage' => 'Manage',
  'Manage All' => 'Manage All',
  'Manage All Charges' => 'Manage All Charges',
  'Manage Charges' => 'Manage Charges',
  'Manage Charges for <em>{name}</em>' => 'Manage Charges for <em>{name}</em>',
  'Manage Projects' => 'Manage Projects',
  'Manage Tasks' => 'Manage Tasks',
  'Manage Users' => 'Manage Users',
  'My Charges' => 'My Charges',
  'My Open Tasks' => 'My Open Tasks',
  'My Profile' => 'My Profile',
  'My Projects' => 'My Projects',
  'My Tasks' => 'My Tasks',
  'My Working On Tasks' => 'My Working On Tasks',
  'Operations' => 'Operations',
  'Project.User.association.{project}' => 'Users associated to {project}',
  'Projects' => 'Projects',
  'Roles' => 'Roles',
  'System' => 'System',
  'Task Status' => 'Task Status',
  'Task Type' => 'Task Type',
  'Tasks' => 'Tasks',
  'Update' => 'Update',
  'Update Attachment' => 'Update Attachment',
  'Update Project' => 'Update Project',
  'Update Role' => 'Update Role',
  'Update Task' => 'Update Task',
  'Update Task Status "{name}"' => 'Update Task Status "{name}"',
  'Update Task Type "{name}"' => 'Update Task Type "{name}"',
  'Update Tasks' => 'Update Tasks',
  'Update User {name}' => 'Update User {name}',
  'Users' => 'Users',
  'Users Online' => 'Users Online',
  'View Attachment' => 'View Attachment',
  //Comments
  'Comments' => 'Comments',
  'Update Comment' => 'Update Comment'
);
