<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Project.charge.courses' => 'Courses',
  'Project.charge.publicHoliday' => 'Public Holiday',
  'Project.charge.sickLeave' => 'Sick-leave',
  'Project.charge.vacation' => 'Vacation',
  'Project.status.chargeItem' => 'Charge Item',
  //2022/07/07 modfiied
  'Project.status.closed' => '完了',
  'Project.status.deleted' => '中止',
  'Project.status.open' => '開始',
  'Project.status.suspended' => '中断',
  'Task.priority.escalated' => '至急',
  'Task.priority.high' => '高',
  'Task.priority.low' => '低',
  'Task.priority.medium' => '普通',
  'Task.type.bug' => 'バグ',
  'Task.type.enh' => '更改',
  'Task.type.task' => 'タスク',
  'TaskStatus.group.closed' => '完了',
  'TaskStatus.group.onHold' => '稼働中',
  'TaskStatus.group.open' => '未着手・開始',
  'User.female' => '女性',
  'User.male' => '男性',
);
