<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  //2022/07/07 modified
  'Add Attachment' => '添付ファイルの追加',
  'All Projects' => 'すべてのプロジェクト',
  'All Tasks' => 'すべてのタスク',
  'Application' => 'アプリケーション',
  'Associate New User' => 'Associate 新規ユーザ',
  'Attachments' => '添付ファイル',
  'Backups' => 'バックアップ',
  'Charges' => '実績',
  'Check for update' => '更新の確認',
  'Config' => '設定',
  'Create' => '作成',
  'Create Charge' => '実績作成',
  'Create Project' => 'プロジェクト作成',
  'Create Role' => '役割作成',
  'Create Task' => 'タスク作成',
  'Create Task Status' => 'タスクステータス作成',
  'Create Task Type' => 'タスクタイプ作成',
  'Create User' => 'ユーザ作成',
  'Database Backups' => 'データベースバックアップ',
  'Delete Confirmation' => 'Delete Confirmation',
  'Edit Profile' => 'プロフィールの編集',
  'Edit Selected' => '選択の編集',
  'Error' => 'エラー',
  'Export to' => 'エクスポート',
  'List' => 'リスト',
  'Login' => 'ログイン',
  'Logout' => 'ログアウト',
  'Manage' => '管理',
  'Manage All' => 'すべての管理',
  'Manage All Charges' => 'すべての実績管理',
  'Manage Charges' => '実績管理',
  'Manage Charges for <em>{name}</em>' => '実績 for 管理<em>{name}</em>',
  'Manage Projects' => 'プロジェクト管理',
  'Manage Tasks' => 'タスク管理',
  'Manage Users' => 'ユーザ管理',
  'My Charges' => 'わたしの実績',
  'My Open Tasks' => 'わたしのオープンタスク',
  'My Profile' => 'わたしのプロフィール',
  'My Projects' => 'わたしのプロジェクト',
  'My Tasks' => 'わたしのタスク',
  'My Working On Tasks' => 'わたしの稼働中タスク',
  'Operations' => 'Operations',
  'Project.User.association.{project}' => 'Users associated to {project}',
  'Projects' => 'プロジェクト',
  'Roles' => '役割',
  'System' => 'システム',
  'Task Status' => 'タスクの状態',
  'Task Type' => 'タスクの種類',
  'Tasks' => 'タスク',
  'Update' => '更新',
  'Update Attachment' => '添付ファイルの更新',
  'Update Project' => 'プロジェクトの更新',
  'Update Role' => '役割更新',
  'Update Task' => 'タスク更新',
  'Update Task Status "{name}"' => 'Update Task Status "{name}"',
  'Update Task Type "{name}"' => 'Update Task Type "{name}"',
  'Update Tasks' => 'すべてのタスク更新',
  'Update User {name}' => 'ユーザ更新 {name}',
  'Users' => 'ユーザ',
  'Users Online' => 'オンラインユーザ',
  'View Attachment' => '添付ファイルの表示',
  //Comments
  'Comments' => 'コメント',
  'Update Comment' => 'コメントの更新'
);
