<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Project.charge.courses' => 'Cours',
  'Project.charge.publicHoliday' => 'Jour férié',
  'Project.charge.sickLeave' => 'Congé de maladie',
  'Project.charge.vacation' => 'Vacances',
  'Project.status.chargeItem' => 'Élément facturé',
  'Project.status.closed' => 'Fermé',
  'Project.status.deleted' => 'Supprimé',
  'Project.status.open' => 'Ouvert',
  'Project.status.suspended' => 'Suspendu',
  'Task.priority.escalated' => 'Intensifiée',
  'Task.priority.high' => 'Haute',
  'Task.priority.low' => 'Basse',
  'Task.priority.medium' => 'Moyenne',
  'Task.type.bug' => 'Bogue',
  'Task.type.enh' => 'Amélioration',
  'Task.type.task' => 'Tâche',
  'TaskStatus.group.closed' => 'Fermé',
  'TaskStatus.group.onHold' => 'En attente',
  'TaskStatus.group.open' => 'Ouvert',
  'User.female' => 'Femme',
  'User.male' => 'Homme',
  'pluralRules' => 
  array (
    0 => '(n>=0&&n<=2)&&n!=2',
    1 => 'true',
  ),
);
