<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */

/**
   Translation completed, but missing plural forms.
 */
return array (
  'Add Attachment' => 'Ajouter une pièce jointe',
  'All Projects' => 'Tous les Projets',
  'All Tasks' => 'Toutes les tâches',
  'Application' => 'Application',
  'Associate New User' => 'Associer un nouvel utilisateur',
  'Attachments' => 'Pièces jointes',
  'Backups' => 'Sauvegardes',
  'Charges' => 'Facturation',
  'Check for update' => 'Vérifier les mises à jour',
  'Config' => 'Configuration',
  'Create' => 'Ajouter',
  'Create Charge' => 'Ajouter à la facturation',
  'Create Project' => 'Créer un projet',
  'Create Role' => 'Créer un rôle',
  'Create Task' => 'Créer une tâche',
  'Create Task Status' => 'Créer un statut de tâche',
  'Create Task Type' => 'Créer un type de tâche',
  'Create User' => 'Créer un utilisateur',
  'Database Backups' => 'Copies de sauvegarde de la base de données',
  'Delete Confirmation' => 'Confirmation de la suppression',
  'Edit Profile' => 'Modifier le profil',
  'Edit Selected' => 'Modifier la sélection',
  'Error' => 'Erreur',
  'Export to' => 'Exporter vers',
  'Home' => 'Accueil',
  'List' => 'Liste',
  'Login' => 'Connexion',
  'Logout' => 'Déconnexion',
  'Manage' => 'Gérer',
  'Manage All' => 'Tout gérer',
  'Manage All Charges' => 'Gérer tous les frais',
  'Manage Charges' => 'Gérer la facturation',
  'Manage Charges for <em>{name}</em>' => 'Gérer la facturation pour <em>{name}</em>',
  'Manage Projects' => 'Gérer les Projets',
  'Manage Tasks' => 'Gérer les tâches',
  'Manage Users' => 'Gérer les utilisateurs',
  'My Charges' => 'Ma facturation',
  'My Open Tasks' => 'Mes tâches ouvertes',
  'My Profile' => 'Mon profil',
  'My Projects' => 'Mes Projets',
  'My Tasks' => 'Mes tâches',
  'My Working On Tasks' => 'Mes tâches en cours',
  'Operations' => 'Opérations',
  'Project.User.association.{project}' => 'Utilisateurs associé à {project}',
  'Projects' => 'Projets',
  'Roles' => 'Rôles',
  'System' => 'Système',
  'Task Status' => 'Statut de la tâche',
  'Task Type' => 'Type de tâche',
  'Tasks' => 'Tâches',
  'Update' => 'Mettre à jour',
  'Update Attachment' => 'Mettre à jour la pièce jointe',
  'Update Project' => 'Mettre à jour le projet',
  'Update Role' => 'Mettre à jour le rôle',
  'Update Task' => 'Mettre à jour la tâche',
  'Update Task Status "{name}"' => 'Mettre à jour le statut de la tâche "{name}"',
  'Update Task Type "{name}"' => 'Mettre à jour le type de la tâche "{name}"',
  'Update Tasks' => 'Mettre à jour les tâches',
  'Update User {name}' => "Mettre à jour l'utilisateur {name}",
  'Users' => 'Utilisateurs',
  'Users Online' => 'Utilisateurs en ligne',
  'View Attachment' => 'Voir les pièces jointes',
  //Comments
  'Comments' => 'Comments',
  'Update Comment' => 'Update Comment',
  'pluralRules' => 
  array (
    0 => '(n>=0&&n<=2)&&n!=2',
    1 => 'true',
  ),
);
